### ISSUE TITLE
Having trouble running via docker 

### ISSUE THREAD

**Issue by monkykap** [ocmdev/rita#147]
This is probably just user error, but I'm having issue using the provided docker-compose configuration. I'm sure that i have set it up correctly according to WIKI steps. 

**[+] Importing /logs
	[-] Finding files to parse
	[-] Indexing log entries. This may take a while.**

Whenever i use sudo docker-compose run show-databases or analyze, there is no output.:

**Starting rita_db_1 ... done**

If i go inside the mongo container and run mongo shell i don't see any new database created. I'm wondering if i should mount the log files in the rita container to see what it is picking up.

Here is my dir:
**/data/rita$ ls**
_Contributing.md  LICENSE   Readme.md  bro       config    datatypes    docker-compose.yaml  install.sh  logs    reporting         rita.go Dockerfile       Makefile  analysis   commands  database  do_stuff.sh  etc                  logmover    parser  rita-docker.yaml  util_

Env variable for bro logs (I manually copied them over to this directory they are in normal formate not json):

**/data/rita$ echo ${BRO_LOGS:-./logs}**
/data/rita/bro/logs

Here are my config files:

_rita-docker.yaml_

```
# Mongo Database to connect to
DatabaseHost: db:27017

LogConfig:
    # LogLevel
    # 3 = debug
    # 2 = info
    # 1 = warn
    # 0 = error
    LogLevel: 3

    # LogPath is the path for Rita's logs, generally this just defaults to
    # $HOME/.rita/logs. Logs will only be written here if LogToFile is true
    RitaLogPath: $HOME/.rita/logs
    LogToFile: true

    RitaLogTable: logs
    LogToDB: true

# The section Bro configures the bro ingestor
Bro:
    # Path to a top level directory of log files
    LogPath: /logs

    # All databases in this test will get prefixed with the database prefix
    DBPrefix: arita

    # Subdirectories of LogPath may be separated into different databases for the
    # test. Map each directory to the database you wish that directory to wind up
    # in. This is good for running tests against multiple subnets and network
    # segments. Put the directory name on the left side of the colon, and the
    # database you wish the logs from that directory to go in on the right side.
    DirectoryMap:
       UniqueDir: SeparateDatabaseName
       UniqueDir2: SeparateDatabaseName2

    # If set, files which don't match the directory map will be placed
    # in this default database.
    #DefaultDatabase: DefaultDatabaseName

    # There needs to be one metadatabase per test. This database holds information
    # about the test and the files related to the test. If there are several
    # subnets mapped in DirectoryMap each will be handled separately and that
    # separation is handled by the metadatabase.
    MetaDB: MetaDatabase

    # If use dates is true the logs will be split into databases by date, this is
    # best for if you have multiple days worth of log files in the logpath and wish
    # to treat each day as a separate test. 24hours worth of data is the ideal for
    # analysis, and using dates will ensure that tests are broken into 24hour periods
    # around midnight of each day.
    UseDates: false

    # The number of records shipped off to MongoDB at a time. Increasing
    # the size of the buffer will improve import timings but will leave more
    # records unimported if there is an error
    ImportBuffer: 100000

SafeBrowsing:
    APIKey: "REDACTED"
    Database: $HOME/.rita/safebrowsing

# NOTE: DO NOT CHANGE THE SETTINGS BELOW UNLESS YOU ARE FAMILIAR WITH THE CODE #
Structure:
    ConnectionTable: conn
    HttpTable: http
    DnsTable: dns
    UniqueConnectionTable: uconn
    HostTable: host

BlackListed:
    ThreadCount: 2
    ChannelSize: 1000
    BlackListTable: blacklisted
    Database: rita-blacklist

Dns:
    ExplodedDnsTable: explodedDns
    HostnamesTable: hostnames

Crossref:
    InternalTable: internXREF
    ExternalTable: externXREF
    BeaconThreshold: .7

Scanning:
    ScanThreshold: 50
    ScanTable: scan

Beacon:
    DefaultConnectionThresh: 24
    BeaconTable: beacon

Urls:
    UrlsTable: urls

UserAgent:
    UserAgentTable: useragent

MetaTables:
    FilesTable: files
    DatabasesTable: databases


# Adjusting batchsize and prefetch may help speed up certain database queries
BatchSize: 300
Prefetch: 0.33

```
_docker-compose.yaml_

```
version: '3'
volumes:
  db:
services:
  db:
    image: mongo
    restart: unless-stopped
    volumes:
      - db:/data/db
  rita:
    image: ocmdev/rita
    volumes:
     - ${BRO_LOGS:-./logs}:/logs/:ro
     - ./rita-docker.yaml:/root/.rita/config.yaml:ro
    links:
      - db
```

**Comment by ethack** [comment]
Unless you're specifying directories and databases manually via command line options, you'll need to change the section of the config file dealing with the log source directories.

```
    # Subdirectories of LogPath may be separated into different databases for the
    # test. Map each directory to the database you wish that directory to wind up
    # in. This is good for running tests against multiple subnets and network
    # segments. Put the directory name on the left side of the colon, and the
    # database you wish the logs from that directory to go in on the right side.
    DirectoryMap:
       UniqueDir: SeparateDatabaseName
       UniqueDir2: SeparateDatabaseName2
```

Or you can set a `DefaultDatabase` to have all the logs go to one database.

```
    # If set, files which don't match the directory map will be placed
    # in this default database.
    #DefaultDatabase: DefaultDatabaseName

```
