### ISSUE TITLE
Mongo connection certificate validation fails

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#151]
I believe that `tlsConf.ServerName` [here](https://github.com/ocmdev/rita/blob/dev/config/running.go#L38-L50) needs to be set if `VerifyCertificate` is `true` in the config file.  I think it should be set based on the host specified in the `ConnectionString` value.  [This function](https://godoc.org/gopkg.in/mgo.v2#ParseURL) should be useful and then possibly use `DialInfo.ServiceHost` as the value.

---

[`crypto/tls`'s documentation](https://golang.org/pkg/crypto/tls/#Config) indicates that the `ServerName` value is required for certificate validation.

```
        // ServerName is used to verify the hostname on the returned
        // certificates unless InsecureSkipVerify is given. It is also included
        // in the client's handshake to support virtual hosting unless it is
        // an IP address.
        ServerName string
```

I have a certificate where the `CN` is `127.0.0.1`, I use `127.0.0.1` in the `ConnectionString` and set `CAFile` to the path to the .pem certificate.  RITA will successfully connect if `VerifyCertificate` is `false` but will refuse if `VerifyCertificate` is `true`.

```
# /etc/mongodb.conf snippet
# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1
  ssl:
    mode: requireSSL
    PEMKeyFile: /etc/ssl/mongodb.pem
```

```
# ~/.rita/config.yaml snippet
MongoDB:
  # See https://docs.mongodb.com/manual/reference/connection-string/
  ConnectionString: mongodb://admin:password@127.0.0.1:27017
  # How to authenticate to MongoDB
  # Accepted Values: null, "SCRAM-SHA-1", "MONGODB-CR", "PLAIN"
  AuthenticationMechanism: SCRAM-SHA-1
  # The time in hours before RITA's connection to MongoDB times out. 0 waits indefinitely.
  SocketTimeout: 2
  # For encrypting data on the wire between RITA and MongoDB
  TLS:
    Enable: true
    #If set, RITA will verify the MongoDB certificate's hostname and validity
    VerifyCertificate: false
    #If set, RITA will use the provided CA file instead of the system's CA's
    CAFile: /etc/ssl/mongodb.pem
```

```
# RITA successfully connects
user@ubuntu:~$ rita show-databases
dnscat
```

```
# Changing VerifyCertificate to true and RITA does not connect
user@ubuntu:~$ rita show-databases
Failed to connect to database: no reachable servers
```

```
# Certificate details snippet
user@ubuntu:/etc/ssl$ openssl x509 -in mongodb.pem -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 11299833216186215044 (0x9cd11270e7f06a84)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=Some-State, O=Internet Widgits Pty Ltd, CN=127.0.0.1
        Validity
            Not Before: Dec  1 19:56:28 2017 GMT
            Not After : Dec  1 19:56:28 2018 GMT
        Subject: C=US, ST=Some-State, O=Internet Widgits Pty Ltd, CN=127.0.0.1
```
